---
- hosts: localhost
  gather_facts: false
  vars:
    deployment_name: nexus
    deployment_namespace: nexus
    kubeconfig_context: 'gke_hacks-with-rogues-4741_us-central1-c_nexus-gke'
  tasks:
    - name: 'Assert required vars'
      assert:
        that:
          - deployment_namespace is defined
          - deployment_name is defined
          - kubeconfig_context is defined
      
    - name: 'Ensure manifests directory exists'
      file:
        path: manifests
        state: directory

    - name: "Template out httpd.conf ConfigMap"
      shell: >
        kubectl create configmap nexus-httpd-conf
        -n {{ deployment_namespace }}
        --dry-run -o yaml
        --from-file files/httpd.conf |
        sed '/creationTimestamp/d' >
        manifests/nexus-httpd-conf-cm.yml

    - name: 'Template out for GitOps'
      template:
        src: "templates/create-{{ item }}.yml.j2"
        dest: "manifests/{{ deployment_name }}-{{ item }}.yml"
      loop:
        - 'ns'
        - 'pvc'
        - 'deploy'
        - 'networking'
