---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1G"
            cpu: "1000m"
          limits:
            memory: "4G"
            cpu: "3920m"
        ports:
        - containerPort: 8081
        - containerPort: 18080
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 6
      - name: httpd
        image: httpd:2.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nexus-httpd-conf-file
          mountPath: /usr/local/apache2/conf/httpd.conf
          subPath: httpd.conf
        command: ['/usr/local/apache2/bin/httpd']
        args: ['-DFOREGROUND']
      volumes:
        - name: nexus-data-volume
          persistentVolumeClaim:
            claimName: nexus-pvc
        - name: nexus-httpd-conf-file
          configMap:
            name: nexus-httpd-conf
            defaultMode: 0644
